apiVersion: apps/v1
kind: Deployment
metadata:
  name: gptbot
  namespace: guru
  labels:
    app: gptbot
  annotations:
    argocd-image-updater.argoproj.io/image-list: gptbot=harbor.local/guru/gptbot
    argocd-image-updater.argoproj.io/gptbot.update-strategy: latest
    argocd-image-updater.argoproj.io/gptbot.allow-tags: regexp:^.*$
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gptbot
  template:
    metadata:
      labels:
        app: gptbot
    spec:
      containers:
        - name: gptbot
          image: harbor.local/guru/gptbot:202503240430
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
      imagePullSecrets:
        - name: harbor-reg-secret
