apiVersion: v1
kind: Service
metadata:
  name: gptbot-service
  namespace: guru
spec:
  selector:
    app: gptbot
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
